# Generated by Django 5.2.4 on 2025-08-12 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, choices=[('Europe', 'Europe'), ('Asia', 'Asia'), ('Africa', 'Africa'), ('Latin America and the Caribbean', 'Latin America and the Caribbean'), ('Oceania', 'Oceania'), ('Middle East', 'Middle East'), ('Other', 'Other')], default='Other', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('environmental_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomies_manager.environmentalobjective')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomies_manager.taxonomy')),
            ],
        ),
        migrations.AddField(
            model_name='environmentalobjective',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomies_manager.taxonomy'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy_code', models.CharField(max_length=50)),
                ('economic_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('contribution_type', models.CharField(choices=[('Enabling', 'Enabling'), ('Transitional', 'Transitional'), ('None', 'None')], default='None', max_length=50)),
                ('sc_criteria_type', models.CharField(choices=[('threshold', 'Threshold'), ('traffic_light', 'Traffic Light')], default='threshold', max_length=50)),
                ('substantial_contribution_criteria', models.TextField(blank=True)),
                ('non_eligibility_criteria', models.TextField(blank=True)),
                ('sc_criteria_green', models.TextField(blank=True)),
                ('sc_criteria_amber', models.TextField(blank=True)),
                ('sc_criteria_red', models.TextField(blank=True)),
                ('dnsh_climate_adaptation', models.TextField(blank=True)),
                ('dnsh_water', models.TextField(blank=True)),
                ('dnsh_circular_economy', models.TextField(blank=True)),
                ('dnsh_pollution_prevention', models.TextField(blank=True)),
                ('dnsh_biodiversity', models.TextField(blank=True)),
                ('dnsh_land_management', models.TextField(blank=True)),
                ('environmental_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomies_manager.environmentalobjective')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomies_manager.sector')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomies_manager.taxonomy')),
            ],
        ),
    ]
