# Generated by Django 5.2.4 on 2025-10-22 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies_manager', '0003_activity_dnsh_climate_mitigation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'verbose_name': 'Practice', 'verbose_name_plural': 'Practices'},
        ),
        migrations.AlterModelOptions(
            name='subsector',
            options={'verbose_name_plural': 'Subsectors'},
        ),
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'verbose_name_plural': 'Taxonomies'},
        ),
        migrations.CreateModel(
            name='AdaptationGeneralCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='ES', max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('criteria', models.TextField(blank=True)),
                ('subcriteria', models.TextField(blank=True)),
                ('environmental_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_general_criteria', to='taxonomies_manager.environmentalobjective')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_general_criteria', to='taxonomies_manager.taxonomy')),
            ],
            options={
                'verbose_name': 'Adaptation general criterion (Case 3)',
                'verbose_name_plural': 'Adaptation general criteria (Case 3)',
                'unique_together': {('taxonomy', 'environmental_objective', 'title')},
            },
        ),
        migrations.CreateModel(
            name='AdaptationWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='ES', max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('eligible_activities', models.TextField(blank=True)),
                ('environmental_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_whitelists', to='taxonomies_manager.environmentalobjective')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_whitelists', to='taxonomies_manager.sector')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_whitelists', to='taxonomies_manager.taxonomy')),
            ],
            options={
                'verbose_name': 'Adaptation whitelist (Case 2)',
                'verbose_name_plural': 'Adaptation whitelists (Case 2)',
                'unique_together': {('taxonomy', 'environmental_objective', 'sector', 'title')},
            },
        ),
    ]
