# Generated by Django 5.2.4 on 2025-10-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies_manager', '0004_alter_activity_options_alter_practice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='adaptationgeneralcriterion',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='adaptationwhitelist',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='practice',
            name='practice_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rwandaadaptation',
            name='hazard',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rwandaadaptation',
            name='sector',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
