# Generated by Django 5.2.4 on 2025-10-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies_manager', '0005_alter_activity_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentalobjective',
            old_name='name',
            new_name='generic_name',
        ),
        migrations.AlterUniqueTogether(
            name='environmentalobjective',
            unique_together={('taxonomy', 'generic_name')},
        ),
        migrations.AddField(
            model_name='environmentalobjective',
            name='display_name',
            field=models.TextField(blank=True),
        ),
    ]
