# Generated by Django 5.2.4 on 2025-10-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies_manager', '0006_rename_name_environmentalobjective_generic_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adaptationgeneralcriterion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='adaptationgeneralcriterion',
            constraint=models.UniqueConstraint(fields=('taxonomy', 'environmental_objective', 'title', 'subcriteria'), name='uniq_agc_tax_obj_title_subcriteria'),
        ),
    ]
